/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'emart_seller';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String IC_LOGO = 'assets/icons/ic_logo.png';
  static const String SPLASH_LOGIN_REGISTRATION_BACKGROUND_IMAGE = 'assets/icons/splash_login_registration_background_image.png';
}
