/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class LibRes {
  static const String PLUGIN_NAME = 'emart_seller';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CATEGORY_MODEL = 'lib/services/category_model.json';
}
