const appname = "eMart Seller App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    emailHint = "vendor@metastore.com",
    password = "Password",
   passwordHint = "********",
    forgotPassword = "Forgot Password?",
    anyProblem = "In case of any difficulty, contact administration",
    credit = "@UmerFarooq",
  dashboard= "Dashboard",
  orders= "Orders",
  products= "Products",
home= "Home",
settings= "Settings",
 logintocontinue= "Login to continue",
rating= "Rating",
totalSales= "Total Sales",
popularProducts= "Popular Products",
unpaid= "Unpaid",
  chat= "Chat",
featured= "Featured",
edit="Edit",
delete="Delete"
;


const nameHint= "ed. vendor Name",
      shopDesHint= "Enter your Shop Description",
      shopName= "Shop Name",
      shopDes= "Shop Description",
      shopAddress= "Shop Address",
      shopAddressHint= "Enter your Shop Address",
      shopMobileHint= "Enter your Shop Mobile Number",
    shopWebHint= "Enter your Shop Website",
    shopWeb= "Shop Website",
vendorName= "Vendor Name",
shopsetting= "Shop Settings",
message= "Message",
save= "Save",
confirmPassword= "Confirm Password",
confirmPasswordHint= "********",
productname= "Product Name",
productnameHint= "Enter your Product Name",
productDes= "Product Description",
productDesHint= "Enter your Product Description",
productPrice= "Product Price",
productPriceHint= "Enter your Product Price",
productQuantity= "Product Quantity",
productQuantityHint= "Enter your Product Quantity",
productCategory= "Product Category",
productCategoryHint= "Enter your Product Category",
productImage= "Product Image",
productImageHint= "Enter your Product Image",
productSubcategory= "Product Subcategory",
productSubcategoryHint= "Enter your Product Subcategory",
    shopMobile= "Shop Mobile Number";
const logOut="User logout Successfully";
const loginSuccess="User Login Successfully";
const loginFailed="User Login Failed";
const appversion = "Version 1.0.0";
const credits = "@UmerFarooq";
const update="Update";
const camera="Camera";
const gallery="Gallery";


